export const NAVIGATE_TO_PAGE = 'QT-NAVIGATE';
export const BREAKING_NEWS_UPDATED = 'QT-BREAKING_NEWS_UPDATED';
export const CLIENT_SIDE_RENDERED = 'QT-CLIENT_SIDE_RENDERED';
export const PAGE_LOADING = 'QT-PAGE_LOADING';
export const PAGE_FINISHED_LOADING = 'QT-PAGE_FINISHED_LOADING';

export const HAMBURGER_CLICKED = 'QT-HAMBURGER_CLICKED';
export const HAMBURGER_CLOSED = 'QT-HAMBURGER_CLOSED';

export const SERVICE_WORKER_UPDATED = 'QT-SERVICE_WORKER_UPDATED';

export const MEMBER_UPDATED = 'QT-MEMBER_UPDATED';
export const MEMBER_BEING_LOADED = 'QT-MEMBER_BEING_LOADED';
